APPS-120 - Added an option to check for single approver
ServiceCanada/x-notify pull request #70
Opened 2022-02-16 17:44 UTC by shiva-sc

2022-02-16 17:47 UTC, shiva-sc commented
@duboisp @jonasg-gc @yeungca2 Please review the PR

2022-02-16 18:15 UTC, jonasg-gc approved these changes
Looks good to me.

2022-02-16 18:16 UTC, jonasg-gc commented
@duboisp : did you also want to review?

2022-02-17 15:01 UTC, duboisp requested changes

2022-02-17 16:19 UTC, duboisp requested changes

2022-02-17 16:19 UTC, duboisp commented on server.js
> +		bodyParser.urlencoded({extended:true, limit: '1024k'}),
Do we need this?

2022-02-17 16:28 UTC, duboisp requested changes

2022-02-17 16:32 UTC, duboisp requested changes

2022-02-17 16:35 UTC, duboisp commented on controllers/mailing_view.js
> +	const subscode = req.params.subscode;
```suggestion
	const subscode = req.params.subscode || "0";
```

2022-02-17 16:43 UTC, duboisp approved these changes
Thanks Shiva

2022-02-17 16:44 UTC, duboisp commented
For the record: This is a MINOR change.

\cc @jonasg-gc

2022-02-17 16:44 UTC, merged