APPS-126 -- added default environment configuration for redis setup
ServiceCanada/x-notify pull request #72
Opened 2022-02-25 05:29 UTC by shiva-sc

2022-02-25 05:30 UTC, shiva-sc commented
@duboisp : Consider this initial draft, we can discuss more about this on Friday

2022-02-25 17:24 UTC, duboisp requested changes

2022-02-25 17:24 UTC, duboisp commented on controllers/subscriptions.js
>  const notifyQueue = new Queue('sendMail',
Can you add logic like this code:
```javascript
if (process.env.NODE_ENV === 'production') {
    var redisConf = {
        redis: {
            sentinels: [
                { host: redisSentinel1Uri, port: redisSentinel1Port },
                { host: redisSentinel2Uri, port: redisSentinel2Port },
            ],
            name: redisMasterName,
        }
    }
} else {
    var redisConf = {
        redis: {
            host: redisUri,
            port: redisPort,
        }
    }
}
```

2022-02-25 17:26 UTC, duboisp reviewed
Don't forget to document those new environment variable here: https://github.com/ServiceCanada/x-notify/blob/master/setup.md#environment-variables

2022-02-25 17:39 UTC, duboisp requested changes

2022-02-25 17:39 UTC, duboisp commented on notifyQueue.js
>  const notifyQueue = new Queue('sendMail',
```suggestion

if ( .... ){ 
redisConf = {}
else {
redisConf = {}
}

const notifyQueue = new Queue('sendMail', redisConf );
```

2022-02-25 19:21 UTC, duboisp requested changes
To not forget, this PR are only missing the documentation of the environment variable and the associated JIRA would need to include special instructions for when the application would be deployed.

2022-02-25 22:55 UTC, shiva-sc commented
@duboisp : I have modified the documentation for environment variable. Can you please review?

2022-02-26 03:03 UTC, duboisp requested changes
Other that the small clarification, the rest look good.

We would only need to provide some instruction in our jira request for the deployment on stage and for the deployment on prod, like what env variable that need to be defined.

2022-02-26 03:03 UTC, duboisp commented on setup.md
> +* `REDIS_ENV` Set environment value for Redis. Default: `stage`
```suggestion
* `REDIS_ENV` Set environment value for Redis. Default: `stage` and for production use which leverage the redis-sentinel, this need to be set to `production`
```

2022-03-10 15:25 UTC, duboisp approved these changes

2022-03-10 15:30 UTC, duboisp requested changes

2022-03-10 15:30 UTC, duboisp commented on notifyQueue.js
> +if (process.env.NODE_ENV === 'production') {
According to documentation (line 77 in setup.md), the value need to be set to:  `prod`

2022-03-23 21:08 UTC, duboisp approved these changes

2022-03-23 21:09 UTC, merged